import { config } from "dotenv";

config();

const {
  PORT,
  MONGODB_URI,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_CERT_URL,
  FIREBASE_CLIENT_CERT_URL,
  OPENAI_API_KEY,
  STRIPE_API_KEY,
  STRIPE_WEBHOOK_SECRET,
  ANTHROPIC_API_KEY,
} = process.env;

export {
  PORT,
  MONGODB_URI,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_CERT_URL,
  FIREBASE_CLIENT_CERT_URL,
  OPENAI_API_KEY,
  STRIPE_API_KEY,
  STRIPE_WEBHOOK_SECRET,
  ANTHROPIC_API_KEY,
};
